services:
  traefik:
    image: traefik:v3
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.rule=Host(`traefik.mix-dev.pl`)"
    - "traefik.http.routers.traefik.entrypoints=websecure"
    - "traefik.http.routers.traefik.tls.certresolver=my-resolver"
    - "traefik.http.routers.traefik.service=api@internal"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.my-resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.my-resolver.acme.email=mikikorolczyk@gmail.com"
      - "--certificatesresolvers.my-resolver.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"

  app:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.rule=Host(`mix-dev.pl`)"
      - "traefik.http.routers.hello.entrypoints=websecure"
      - "traefik.http.routers.hello.tls.certresolver=my-resolver"
      - "traefik.http.services.hello-svc.loadbalancer.server.port=80"
      - "traefik.http.routers.hello.service=hello-svc"
  
  dick-backend:
    image: mixon27/mix-dev:dick_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dick-backend.rule=Host(`dick-api.mix-dev.pl`)"
      - "traefik.http.routers.dick-backend.entrypoints=websecure"
      - "traefik.http.routers.dick-backend.tls.certresolver=my-resolver"
      - "traefik.http.services.dick-backend-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.dick-backend.service=dick-backend-svc"

volumes:
  letsencrypt:
